name: Publish And Deploy Demo # 自动部署的名称
on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 运行环境，告诉它运行在什么环境 我们选择使用最新的ubuntu系统
    steps:

    # 下载源码 （CI/CD拉取代码到自己的本地）
    - name: Checkout 
      uses: actions/checkout@master  # 将代码拷贝到虚机中

    # 部署到服务器
    - name: Deploy
      uses:JamesIves/github-pages-deploy-action@master 
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }} # 使用刚新建的secret
        BRANCH: gh-pages # 存放产物的分支名称
        FOLDER: dist # 存放build后产物的目录
        BUILD_SCRIPT: npm install && npm run build # 执行的命令
        # BUILD_SCRIPT: export VUE_APP_ENV_TEST="${{ secrets.ENV_TEST }}" && npm install && npm run build # 执行的命令

      #uses: appleboy/ssh-action@master # 使用ssh链接服务器
      #with:
      #  host: ${{ secrets.HOST }}
      #  username: ${{ secrets.USERNAME }}
       # password: ${{ secrets.PASSWORD }}
        #port: ${{ secrets.PORT }}
        #script: | # 执行命令（运行到服务器）cd：要确保服务器有这个目录； wget：下载上一步的release到服务器； tar：解压； 安装依赖；启动服务
         # cd /root/zhcs
          #wget https://github.com/cloveryuan/zhcs_bigscreen/releases/latest/download/release.tgz -O release.tgz
          #tar zxvf release.tgz
          #npm install --production
          #pm2 reload pm2.config.json
